{
 "title": "kubernetes资源全面展示",
 "description": "【中文版本】2021.10.10更新，kubernetes资源全面展示！包含K8S整体资源总览、微服务资源明细、Pod资源明细及K8S网络带宽，优化重要指标展示。https://github.com/starsliao/Prometheus",
 "tags": [
  "StarsL.cn",
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "集群", "query": "prometheus" },
   {
    "name": "Host",
    "label": "主机名",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job.*\"}, nodename)"
    }
   },
   {
    "name": "Node",
    "label": "节点",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job.*\",nodename=~\"$Host\"}, instance)"
    }
   },
   { "name": "NameSpace", "label": "命名空间", "query": { "query": "label_values(namespace)" } },
   { "name": "Container", "label": "微服务(容器名)", "query": { "query": "label_values(container)" } },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "Filters" },
   {
    "name": "mountpoint",
    "label": "挂载盘",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{device !=\"tmpfs\"},mountpoint)"
    }
   },
   { "name": "Mypod", "label": "Pod名称【模糊匹配】" }
  ]
 },
 "panels": [
  {
   "title": "K8S 集群资源分配情况 所选集群: $datasource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Control Plane UP",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(up{job=~\"apiserver|kube-scheduler|kube-controller-manager\"} == 0)"
      }
     ]
    },
    {
     "title": "Alerts Firing",
     "type": "stat",
     "description": "正在发生的告警数量",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ALERTS{alertstate=\"firing\",alertname!=\"DeadMansSwitch\"})"
      }
     ]
    },
    {
     "title": "Alerts Pending",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ALERTS{alertstate=\"pending\",alertname!=\"DeadMansSwitch\"})"
      }
     ]
    },
    {
     "title": "Node Disk Pressure",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Node Memory Pressure",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})"
      }
     ]
    },
    {
     "title": "Node Not Ready",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"Ready\",status!=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unschedulable",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Crashing Control Plane Pods",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(increase(kube_pod_container_status_restarts{namespace=~\"kube-system\"}[1h]) > 5)"
      }
     ]
    },
    {
     "title": "Memory Requests (%)  $Node 【已分配资源】",
     "type": "gauge",
     "description": "K8S Node 内存请求率,值越大说明可调度资源越少",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node) *100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Requests (%)  $Node【已分配资源】",
     "type": "gauge",
     "description": "K8S Node CPU请求率,值越大说明可调度资源越少\n\nsum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node) *100",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node) *100",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S 名称空间资源分配情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Quota",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(mixin_pod_workload) by (namespace)"
      },
      {
       "expr": "count(avg(mixin_pod_workload) by (workload, namespace)) by (namespace)"
      },
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
      },
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
      },
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores) by (namespace)"
      }
     ]
    },
    {
     "title": "Requests by Namespace",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(mixin_pod_workload) by (namespace)"
      },
      {
       "expr": "count(avg(mixin_pod_workload) by (workload, namespace)) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{ container!=\"\"}) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{ container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes) by (namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
      },
      {
       "expr": "sum(container_memory_rss{ container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S 节点内存使用【free -m】$Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "free -m 内存使用率(可关联节点) 【系统层面】$Node",
     "type": "gauge",
     "description": "此处计算值为free -m 中的: (1 - available/total)*100",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$Node\"} / (node_memory_MemTotal_bytes{instance=~\"$Node\"})))* 100",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "集群负载情况  辅助性能问题排查 所选集群: $datasource",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Node 节点CPU核数",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_cpu_seconds_total{cluster=\"\", job=\"node-exporter\",  instance=~\"^$Node$\", mode=\"user\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "$Node: 系统负载情况",
     "type": "graph",
     "description": "统计系统 1  5  15 分钟的负载情况",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(node_load1{cluster=\"\", job=\"node-exporter\", instance=~\"^$Node$\"}) by (instance)",
       "legendFormat": "{{instance}} ==>1分钟"
      },
      {
       "expr": "max(node_load5{cluster=\"\", job=\"node-exporter\", instance=~\"^$Node$\"}) by (instance)",
       "legendFormat": "{{instance}}==>5分钟"
      },
      {
       "expr": "max(node_load15{cluster=\"\", job=\"node-exporter\",  instance=~\"^$Node$\"}) by (instance)",
       "legendFormat": "{{instance}}==>15分钟"
      }
     ]
    },
    {
     "title": "$Node：节点内存情况  (主机维度计算)",
     "type": "graph",
     "description": "计算方法:   free  -m \n(1- available/total)*100",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$Node\"} / (node_memory_MemTotal_bytes{instance=~\"$Node\"})))* 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "$Node：节点2min内CPU使用情况  (主机维度计算 2min)",
     "type": "graph",
     "description": "计算公式为:100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) ",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{instance=~\"$Node\",mode=\"idle\"}[2m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "5分钟  Disk R/W Data  $Node",
     "type": "graph",
     "description": "磁盘读写\nirate(node_disk_read_bytes_total{instance=~\"$Node\",job=~\"$job\"}[5m])",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$Node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{instance}}==>{{device}} - Read bytes"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$Node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{instance}}==>{{device}} - Written bytes"
      }
     ]
    },
    {
     "title": "每次IO读写的耗时（参考：小于100ms）$Node",
     "type": "graph",
     "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "s", "label": "读取（-）/写入（+）" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$Node\"}[30m]) / irate(node_disk_reads_completed_total{instance=~\"$Node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_读取"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$Node\"}[30m]) / irate(node_disk_writes_completed_total{instance=~\"$Node\"}[30m])",
       "legendFormat": "{{instance}}_{{device}}_写入"
      }
     ]
    },
    {
     "title": "[5m] Disk IOps Completed $Node",
     "type": "graph",
     "description": "磁盘IOPS\nirate(node_disk_reads_completed_total{instance=~\"$Node\",job=~\"$job\"}[5m])\nirate(node_disk_writes_completed_total{instance=~\"$Node\",job=~\"$job\"}[5m])",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$Node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{instance}}==>{{device}} - Reads completed"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$Node\",job=~\"$job\"}[5m])",
       "legendFormat": "{{instance}}==>{{device}} - Writes completed"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod 容器内存使用 $Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "容器内存使用情况【未选择Pod则统计容器总和】",
     "type": "timeseries",
     "description": "包含WSS  RSS  Cache  Swap",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{namespace=~\"$NameSpace\", pod=~\"$Pod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "WSS=>{{container}}"
      },
      {
       "expr": "sum(container_memory_swap{namespace=~\"$NameSpace\", pod=~\"$Pod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "Swap=>{{container}}"
      },
      {
       "expr": "sum(container_memory_cache{namespace=~\"$NameSpace\", pod=~\"$Pod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "Cache=>{{container}}"
      },
      {
       "expr": "sum(container_memory_rss{namespace=~\"$NameSpace\", pod=~\"$Pod\", container!=\"POD\", container!=\"\"}) by (container)",
       "legendFormat": "RSS=>{{container}}"
      }
     ]
    },
    {
     "title": "Pods 内存使用【Pod名称或模糊匹配二选一】",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",pod=~\"^.*$Mypod.*\"} and container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",pod=~\"$Pod\"}) by (pod,node)",
       "legendFormat": "{{ node }}=>{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod容器内存使用率(可关联节点)",
     "type": "timeseries",
     "description": "节点与Pod不能同时进行关联\n未设置Limits的将无法计算使用率",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "WSS%：{{ pod }}"
      },
      {
       "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "RSS%：{{ pod }}"
      },
      {
       "expr": "(cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$NameSpace\"}) / (cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{pod=~\"$Pod\",namespace=~\"$NameSpace\"}) * 100",
       "legendFormat": "Heap%：{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod CPU使用$Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 使用情况【未选择Pod则统计容器总和】",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=~\"$NameSpace\", pod=~\"$Pod\", container!=\"POD\"}) by (container)",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Pod容器CPU使用率(最大100%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}/100000) by (container, pod)) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod 网络使用 $Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod每秒网络带宽 (可关联节点)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(pod) *8",
       "legendFormat": "流入:{{ pod}}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(pod) *8",
       "legendFormat": "流出:{{ pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod 资源总览【可评估资源配额合理性】：所选Pod:【$Pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Node：Pod资源明细(可关联节点)",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}/100000) by (container, pod,node,namespace)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "CPU核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace) * 100",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace) * 100",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"} * on (pod) group_left(node) kube_pod_info{pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "主机容器节点资源使用情况 $Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Node：节点CPU明细  (容器集群维度计算)",
     "type": "graph",
     "description": "计算方式为: (节点上容器总CPU使用/节点上可用于分配的CPU总数 )*100 时间2min\nPS:总CPU会减去k8s组件预留部分",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)*100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$Node：节点内存明细 (容器集群维度计算)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)*100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$Node：节点网络总览",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum (irate(container_network_receive_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
       "legendFormat": "流入:{{node}}"
      },
      {
       "expr": "sum (irate(container_network_transmit_bytes_total{node=~\"^$Node$\"}[2m]))by (node) *8",
       "legendFormat": "流出:{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "节点资源总览：所选节点:【$Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "节点内存比例",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "内存使用率"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "内存请求率"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{esource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "内存限制率"
      }
     ]
    },
    {
     "title": "节点CPU比例",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU使用率"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU请求率"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU限制率"
      }
     ]
    },
    {
     "title": "节点与Pod",
     "type": "bargauge",
     "description": "集群节点数，节点POD数，节点POD上限",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "count(kube_node_info)", "legendFormat": "节点数" },
      {
       "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
       "legendFormat": "Pod数"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
       "legendFormat": "上限Pod"
      }
     ]
    },
    {
     "title": "$NameSpace：网络总览（关联节点与命名空间）",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_network_receive_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
       "legendFormat": "接收"
      },
      {
       "expr": "sum (rate(container_network_transmit_bytes_total{node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
       "legendFormat": "发送"
      }
     ]
    },
    {
     "title": "节点内存信息",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "总内存"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})",
       "legendFormat": "使用量"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
       "legendFormat": "请求量"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
       "legendFormat": "限制量"
      }
     ]
    },
    {
     "title": "节点CPU核数",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "总核数"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{id=\"/\",node=~\"^$Node$\"}[2m]))",
       "legendFormat": "使用量"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "请求量"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "限制量"
      }
     ]
    },
    {
     "title": "节点存储信息",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
       "legendFormat": "使用率"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
       "legendFormat": "使用量"
      },
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
       "legendFormat": "总量"
      }
     ]
    },
    {
     "title": "$Node：节点信息明细",
     "type": "table",
     "description": "此处的内存使用计算方式为: kubectl  top pods显示的总和 ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
       "legendFormat": "pod数"
      },
      {
       "expr": "kube_node_status_condition{status=\"true\",node=~\"^$Node$\"}  == 1",
       "legendFormat": "状态"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m])) by (node)"
      },
      {
       "expr": "kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "内存使用%"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "内存请求%"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "内存限制%"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU使用%"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU请求%"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "内存限制%"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "磁盘使用%"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "Pod上限"
      }
     ]
    }
   ]
  },
  {
   "title": "主机磁盘使用情况 $Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Node 宿主机磁盘使用率",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(mountpoint, node) ((1 - sum by(instance, namespace, pod, mountpoint) (node_filesystem_avail_bytes{instance=~\"$Node\",fstype=~\"xfs|ext4\",job=\"node-exporter\", mountpoint=~\".*disk.*|/|/home\"}) / sum by(instance, namespace, pod, mountpoint) (node_filesystem_size_bytes{instance=~\"$Node\",fstype=~\"xfs|ext4\",job=\"node-exporter\", mountpoint=~\".*disk.*|/|/home\"})) * on(namespace, pod) group_left(node) kube_pod_info)"
      }
     ]
    },
    {
     "title": "主机磁盘使用趋势",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$Node\",job=~\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"$Node\",job=~\"$job\",device!~'rootfs',mountpoint=~\".*disk.*|/|/home\"})",
       "legendFormat": "{{instance}}=>{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "微服务(容器名)资源总览：所选微服务:【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "微服务(容器名)资源统计",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "整体核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "平均内存%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "总内存使用(RSS) "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace) - 0"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体CPU使用率(最大100%)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体内存使用率",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)每秒网络带宽 (可关联节点)",
     "type": "graph",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "流入:{{ container }}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "流出:{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "异常状态的Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "处于waiting状态的容器",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod, container, reason) (kube_pod_container_status_waiting_reason==1)"
      }
     ]
    },
    {
     "title": "异常Pod",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "sum by(namespace, pod,phase) (kube_pod_status_phase{job=\"kube-state-metrics\",phase !=\"Running\"}) > 0"
      }
     ]
    }
   ]
  },
  {
   "title": "最近5天发生过OOMKilled的容器 【$NameSpace】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "$NameSpace  最近5天发生过OOM的容器",
     "type": "table",
     "description": "发生OOM的容器\n【非OOM发生时间】",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (namespace, pod, container, reason) ((kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 5d >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}[5d]) == 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S 集群节点信息展示",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S 节点 lables信息",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum(kube_node_labels) by (label_cluster,label_hostname,label_tag,label_kubernetes_io_hostname)"
      }
     ]
    },
    {
     "title": "K8S 节点污点调度信息",
     "type": "table",
     "description": "K8S 节点污点调度信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(kube_node_spec_taint) by (node,effect,key)"
      }
     ]
    }
   ]
  }
 ]
}